---
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      DATABASE_URL: '${DATABASE_URL}'
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  postgres:
    image: postgres:17.0-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:8.0-alpine
    container_name: redis_db
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command:
      - redis-server
      - --requirepass "${REDIS_PASSWORD}"
      - --user default on >"${REDIS_PASSWORD}"
      - --user "${REDIS_USERNAME}" on >"${REDIS_PASSWORD}" +@all +@dangerous +info ~*
    volumes:
      - redis_data:/data
    networks:
      - app_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
